# Generated by Django 4.2.4 on 2023-08-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traits", "0001_initial"),
        ("pets", "0002_pet_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="trait",
            field=models.ManyToManyField(to="traits.trait"),
        ),
    ]
