# Generated by Django 4.2.4 on 2023-08-11 20:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0003_pet_trait"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pet",
            name="trait",
        ),
    ]
