# Generated by Django 4.2.4 on 2023-08-11 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("traits", "0001_initial"),
        ("groups", "0001_initial"),
        ("pets", "0005_pet_trait"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pets",
                to="groups.group",
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="trait",
            field=models.ManyToManyField(related_name="pets", to="traits.trait"),
        ),
    ]
